### ISSUE TITLE
Update Angular to v13

### ISSUE THREAD

**Issue by yutaro-elk** [UnUniFi/web-apps#238]
**TODO**
- [x] @angular/cdk       12.2.13 -> 13.3.9  ng update @angular/cdk@13
- [x] @angular/cli       12.2.17 -> 13.3.8  ng update @angular/cli@13
- [x] @angular/core      12.2.16 -> 13.3.9  ng update @angular/core@13
- [x] @angular/material  12.2.13 -> 13.3.9  ng update @angular/material@13
- [x] remove @ngrx/store

**Question**
- @KimuraYu45z  "@ngrx/store" is not used, can I delete it?

**Comment by KimuraYu45z** [comment]
ok please delete

**Comment by KimuraYu45z** [comment]
ng-loading-dialog may emit warning or error because of incompatible peer dependency but you can ignore by adding force flag.
